name: 'WordPress Plugin Check'
on:
  pull_request:
  push:
    branches:
    - master
    - 'releases/*'
    - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

        - name: Exclude hidden files and test-api.php
          run: |
          find . -type f -name ".*" -exec rm -f {} \;
          rm -f test-api.php

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
